package com.example.zikr


class Zikrovi() {

    var lista = ArrayList<String>()


    init {
        popuniListu()
    }



    fun popuniListu() {
        lista.add("”Spominjanje Allaha je najveći ibadet. Allah sigurno zna šta vi radite! (Ankebut, 45)")
        lista.add("”Allaha puno spominjite, pa ćete biti spašeni!” (Džumu'a, 10)")
        lista.add("Govoreći o iskrenim vjernicima Uzvišeni Allah kaže da su to oni: ” … koji stojeći, sjedeći i ležeći veličaju Allaha i razmišljaju o stvaranju nebesa i Zemlje …” (Ali Imran, 191)")
        lista.add("Muaz b. Džebbel prenosi da je Resulullah, a.s., rekao: ”Džennetlije neće ni za čim  ovosvjetskim više žaliti kao za vremenom i minutama koje su na dunjaluku proveli a u kojima nisu veličali i spominjali Allaha /činili zikr/!” (Taberani)")
        lista.add("”Spominjanje Allaha je najveći ibadet. Allah sigurno zna šta vi radite! (Ankebut, 45)")
        lista.add("”Allaha puno spominjite, pa ćete biti spašeni!” (Džumu'a, 10)")
        lista.add("Zikrullah je sebeb tome da budeš čuvan pri nesrećama. ")
        lista.add("Zikrullah u lahkoći i ljepoti čini da budeš čuvan u teškoći. ")
        lista.add("Zikrullah spašava Zakira (osoba koja čini zikr) od Allahove dž.š., kazne. ")
        lista.add("Zikrullah priskrbljava Zakiru mir i milost i meleke. ")
        lista.add("Zikrullah jača srce i tijelo. ")
        lista.add("Zikrullah osvijetljava lice i srce. ")
        lista.add("Zikrullah priskrbljava nafaku. ")
        lista.add("Zikrullah daje Zakiru poštovanje, ugled i blještavilo. ")
        lista.add("Zikrullah priskrbljava Zakiru Allahovu dž.š., ljubav. ")
        lista.add("Zikrullah priskrbljava Zakiru svjesnost da je pod stalnom kontrolom Allaha dž.š.. ")
        lista.add("Zikrullah priskrbljava Zakiru neprestano pokajanje i vraćanje Allahu dž.š.. ")
        lista.add("Zikrullah čini Zakira da je uvjek u blizini Allaha dž.š.. ")
        lista.add("Zikrullah priskrbljava Zakiru široku spoznaju svega. ")
        lista.add("Zikrullah priskrbljava Zakiru to da ima veliko strahopoštovanje spram Allaha dž.š.. ")
        lista.add("Zikrullah priskrbljava Zakiru to da i njega Allah dž.š., zikr čini. ")
        lista.add("Zikrullah daje srcu život poput vode ribi. ")
        lista.add("Zikrullah je hrana za srce i dušu. ")
        lista.add("Zikrullah je lijek za bolesti srca. ")
        lista.add("Zikrullah briše i otklanja grijehe. ")
        lista.add("Zikrullah povećava vezu između roba i Rabba. ")
        lista.add("Zikrullah čini Allaha dž.š., zadovoljnim. ")
        lista.add("Zikrullah tjera šejtana, slabi ga i lomi. ")
        lista.add("Zikrullah otklanja brigu i tugu sa srca. ")
        lista.add("Zikrullah u srce unosi radost i veselje. ")
        lista.add("Zikrullahom se čuvamo od gibeta, nemimeta, laži, ogavnosti… ")
        lista.add("Medžlisi zikra su medžlisi meleka dok su medžlisi gafleta medžlisi šejtana. ")
        lista.add("Zakir svojim zikrullahom valja i sebi i drugima za razliku od gafila.")
        lista.add("Zikrullah čini Zakira bezbjednim od stradanja na Sudnjemu Danu. ")
        lista.add("Zikrullah popraćen plačom i samoćom je sebeb tome da Allah dž.š., takvog Zakira stavi u hlad Arša onda kada će ostali ljudi biti u najvećim žegama. ")
        lista.add("Zikrullah je sebeb Allahovom dž.š., davanju. ")
        lista.add("Zikrullah je najlakši ibadet ali je i pored toga najvrijedniji. ")
        lista.add("Zikrullah je džennetsko sjeme. ")
        lista.add("Nagrade priređene za zikrullah nisu kao i nagrade priređene za ostala djela. ")
        lista.add("Neprestani zikrullah nas čini sigurnim od belaja i nesreća koje nastaju onda kada zaboravimo na Allaha dž.š.. ")
        lista.add("Zikr je neprestano uz Allahovog dž.š., roba u svakom halu u kojem se nađe. ")
        lista.add("Zikrullah je svjetlo za Zakira na dunjaluku, i sjutra u grobu, i u vrijeme proživljenja, i u toku prelaska Sirat-ćuprije; ništa ne osvjetljava srca i grobove kao Zikrullah. ")
        lista.add("Zikrullah su vrata na koja se ulazi k Allahu dž.š., pa kome se ona otvore neka ulazi. ")
        lista.add("Srčanu praznoću može ispuniti samo zikrullah. ")
        lista.add("Zikrullah spaja razbijenost srca a razbija spojenost briga i muka i grijeha i šejtana. Približava udaljeno a to je ahiret, i udaljava blizo a to je dunjaluk. ")
        lista.add("Zikrullah je alarm za buđenje srca. ")
        lista.add("Zikrullah je drvo koje urađa plodovima raznih spoznaja i halova. ")
        lista.add("Zikrullah stavlja Zakira u posebnu blizinu kod Allaha dž.š.. ")
        lista.add("Zikrullah zna biti u ravni sa oslobađanjem roba, ili dijeljenjem imetka na Allahovom dž.š., putu, ili čak i sa samom borbom na Allahovom dž.š., putu. ")
        lista.add("Zikrullah je temelj zahvale tj. neće biti zahvalan onaj koji se Allaha dž.š., ne sjeti! ")
        lista.add("Najčasnije stvorenje kod Allaha dž.š., je ona osoba čiji je jezik neprestano vlažan od zikrullaha. ")
        lista.add("Surovost i tvrdoću srca ne može otkloniti ništa osim zikrullaha. ")
        lista.add("Pošto je gaflet bolest srca onda mu je zikrullah lijek. ")
        lista.add("Zikrullah je osnov prijateljstva sa Allahom dž.š., dok je gaflet osnov neprijateljstva sa Allahom dž.š.. ")
        lista.add("Zikrullah najbolje priskrbljava Allahove dž.š., blagodati i ni’imete, i najbolje od nas odbija nesreće. ")
        lista.add("Zikrullah priskrbljava Zakiru salevate od Allaha dž.š., i Njegovih meleka. ")
        lista.add("Kome se šeta kroz džennetske bašče nek’ se drži zikrullaha. ")
        lista.add("Meleki prisustvuju samo onim medžlisima gdje se Allah dž.š., spominje. ")
        lista.add("Allah dž.š., izaziva meleke mnoštvom i istrajnošću ljudi-Zakira, i diči se njima. ")
        lista.add("Zakiri će ući u džennet veselo i smijući se. ")
        lista.add("Sva djela su propisana radi zikrullaha. ")
        lista.add("Najboljeg je djela ona osoba koja je isto to djelo najviše propratila zikrom. ")
        lista.add("Stalni zikr mjenja ostale nafile. ")
        lista.add("Zikrullah najbolje pomaže u pokornosti i ibadetu Allahu dž.š.. ")
        lista.add("Zikrullah olakšava sve što je teško. ")
        lista.add("Zikrullah otklanja strah od srca. ")
        lista.add("Zikrullah priskrbljava Zakiru posebnu snagu. ")
        lista.add("Džennetlije su sve u trci i takmičenju ali će Zakiri biti prvi. ")
        lista.add("Ko čini zikullah Allah dž.š., mu potvrđuje da istinu zbori, pa je za nadati se da će biti upisan međ’ siddike-istinite. ")
        lista.add("Džennetske kuće se izgrađuju pomoću zikra, pa kada čovjek prestane sa zikrullahom – prestanu i meleki praviti kuće jer je ponestalo novca! ")
        lista.add("Zikrullah je brana između čovjeka i džehennemske vatre. ")
        lista.add("Meleki traže oprosta Zakiru isto kao što traže i Ta’ibu-pokajniku. ")
        lista.add("Planinama i dolinama je drago zbog zikra kojeg tuda čine Zakiri. ")
        lista.add("Česti zikrullah čovjeka čuva od munafikluka i licemjerstva. ")
        lista.add("Zikrullah ima poseban lezzet i slast. ")
        lista.add("Zikrullah daje posebno svjetlo licu kako na dunjaluku tako i na ahiretu. ")
        lista.add("Što više zikrullaha ulicom, u džamiji, u kući, na putu itd., više je mjesta koja će ti biti svjedokom na Sudnjemu Danu. ")
        lista.add("Bavljenje zikrullahom znači nebavljenje lošom pričom. ")
        lista.add("Šejtani nemaju utjecaja nad nekim dok postoji zikrullah. ")
        lista.add("Zikrullah je bolji od dove. ")
        lista.add("Dova se najbolje prima nakon zikrullaha. ")
        lista.add("Plemeniti Allah kaže: ''Ti reci: ‘Za moga Gospodara beznačajni ste vi ako nema molbi vaših...'' (El-Furkan, 77")
        lista.add("Hadisi-kudsi: “O sine Ademov, dok god Me budeš molio i od Mene se nadao, Ja ću ti praštati šta god budeš radio, i na to se neću obazirati! O sine Ademov, kad bi tvoji grijesi dosegli do neba, pa Me ti zamolio za oprost, oprostio bih ti! O sine Ademov, kad bi mi pristupio s greškama velikim poput Zemlje, zatim Me sreo ne smatrajući drugog ravnim Meni, Ja bih ti pristupio s isto toliko oprosta!” (Et-Tirmizi)")
        lista.add(" Ibn Qajjim, rahimehullah rekao je:“Zikr za srce je poput vode za ribe. U kakvom će stanju biti riba kada napusti vodu“.")
        lista.add("Poslanik, sallallahu alejhi ve selem rekao:“Primjer onoga koji spominje Allaha, dž.š i primjer onoga koji Ga ne spominje je kao primjer živoga i mrtvoga“. (Muttefekun alejhi) ")
        lista.add("Jedan ashab se požalio Poslaniku na brojnost propisa pa je tražio od njega da ga uputi na najbitnije od njih, na šta mu je Poslanik kazao: „ Neka ti jezik stalno bude vlažan od zikrullaha-spominjanje Allaha.“ ")
        lista.add("„Allah dž.š., kaže: Ja sam s Mojim Robom kad god Me se on sjeti. Ja sam s Mojim robom onda kada Me spomene (zikr) – ako Me spomene u sebi, spomenuću ga u Sebi, a ako Me spomene u društvu – Ja ću ga spomenuti u časnijem društvu od toga. Ako Mi se Moj rob primakne za pedalj – približiću mu se za lakat, a ako Mi se primakne za lakat – približiću mu se za hvat. Ako mi dođe pješice – doći ću mu trčeći!“ (Muttefekun 'alejh) ")
        lista.add("Uzvišenom Allahu su drage osobe koje mnogo zikr čine. Takvima Allah obećava zauzvrat nagradu: „ ...i muškarcima koji mnogo spominju Allaha, i ženama koje mnogo spominju Allaha, Allah je njima pripremio oprost i nagradu golemu! „ (33:35) ")
        lista.add("Prenosi Muaz ibn Džebel, radijallahu anhu, da je Poslanik, sallallahu alejhi ve sellem, rekao: „Želite li da vas obavijestim koje je najbolje vaše djelo, najčistije kod vašeg Gospodara, najviše u vašim deredžama, koje vam je bolje od dijeljenja zlata i srebra i od toga da se susretnete sa neprijateljem i udarate ih po vratovima i oni udaraju vas?“ Rekoše: „Hoćemo Allahov Poslaniče!“ Reče: „Zikr (spominjanje) Allaha, azze ve dželle!“ (Ahmed) ")
        lista.add("Kaže Abdullah ibn Mes’ud, radijallahu anhu: „Da činim tesbih Allahu (izgovaram subhanallah), draže mi je nego da isto toliko podijelim dinara na Allahovu putu!“ ")
        lista.add("Svemilosni je objavio: “O vjernici, često Allaha spominjite i hvalite, i ujutro i navečer Ga veličajte” (El-Ahzab, 41–42) ")
        lista.add(" One koji vjeruju i čija se srca, kad se Allah spomene, smiruju – a srca se doista, kad se Allah spomene, smiruju! (Er-Rad, 28.) ")
        lista.add("I spominji ime Gospodara svoga i Njemu se potpuno posveti. (El-Muzzemmil, 8.) ")
        lista.add("Spominjanje Allaha je najveća poslušnost! (El-Ankebut, 45.) ")
        lista.add("Poslanik, sallallahu alejhi ve sellem, rekao: „Uzvišeni Allah je rekao: 'Ja sam uz mišljenje Mog roba o Meni i Ja sam uz njega kada me spomene. Ako Me spomene u sebi Ja njega spomenem u sebi, a ako Me spomene u društvu ja njega spomenem u društvu boljem od njih. Ako Mi se približi koliko jedan pedalj Ja se njemu približim za dužinu podlaktice, a ako se on Meni približi za podlakticu Ja se njemu približim za dužinu raširenih ruku. Ako se prema Meni uputi običnim korakom Ja se njemu uputim žureći.'“ (Muttefekun alejh) ")
        lista.add("Aiša, radijallahu anhu, je rekla: „Poslanik, sallallahu alejhi ve sellem, je spominjao Allaha u svim svojim stanjima.“ (Bilježi Muslim) ")
        lista.add("Abdullah ibn Busr, radijallahu anhu, prenosi da je jedan čovjek rekao: „Allahov Poslaniče, islamski propisi su za mene mnogobrojni, pouči me nečem čega ću se držati.“ Poslanik, sallallahu alejhi ve sellem, je rekao: „Neka ti jezik stalno bude vlažan spominjući Allaha!“ (Bilježi Tirmizi i Ibnu Madže) ")
        lista.add("Ebu Derda, radijallahu anhu, prenosi da je Poslanik, sallallahu alejhi ve sellem, rekao: „Hoćete li da vas obavijestim o djelima koja su za vas najbolja, najčišća kod vašeg Vladara, najviše podižu vaše stepene, bolja su vam od udjeljivanja zlata i srebra i bolja su vam od toga da se sretnete sa vašim neprijateljem pa siječete njihove vratove a oni vaše!“ „Svakako!“, odgovorše oni, a Poslanik, sallallahu alejhi ve sellem, reče: „To je spominjanje Uzvišenog Allaha!“ (Bilježi Tirmizi i Ibnu Madže) ")
        lista.add("Ebu Hurejre i Ebu Seid el-Hudri, radijallahu anhu, prenose da je Allahov Poslanik, sallallahu alejhi ve sellem, rekao: „Neće se sastati skupina onih koji Uzvišenog Allaha spominju, a da ih neće okružiti meleki, prekriti ih milost, na njih se spustiti smirenost i da ih Allah neće spomenuti kod onih koji su kod Njega.“ (Bilježi Muslim) ")
        lista.add("A onaj ko okrene glavu od Knjige Moje, taj će teškim životom živjeti i na Sudnjem danu ćemo ga slijepim oživiti. Gospodaru moj – reći će – zašto si me slijepa oživio kada sam vid imao? Evo zašto – reći će On: Dokazi Naši su ti dolazili, ali si ih zaboravljao, pa ćeš danas ti isto tako biti zaboravljen. (Ta-ha, 124-126) ")
        lista.add(" Onome ko se bude slijepim pravio da ne bi Milostivog veličao, Mi ćemo šejtana natovariti, pa će mu on nerazdvojni drug postati; oni će ih od Pravoga puta odvraćati, a ljudi će misliti da su na Pravome putu. (Ez-Zuhruf, 36-37.) ")
        lista.add(": O vjernici, neka vas imanja vaša i djeca vaša ne zabave od sjećanja na Allaha. A oni koji to učine, biće izgubljeni. (El-Munafikun, 9.) ")
        lista.add("Od Ebu Zerra, radijallahu anhu, prenosi se da je rekao: “Allahov Poslanik, sallallahu alejhi ve sellem, rekao mi je: ‘Hoćeš li da ti kažem koje su riječi najdraže Allahu? Zaista su Allahu najdraže riječi: SUBHANALLAHI VE BI HAMDIHI – Neka je slavljen i hvaljen Uzvišeni Allah.” (Muslim) ")
        lista.add("Od Ebu Hurejre, radijallahu anhu, prenosi se da je Poslanik, sallallahu alejhi ve sellem, rekao: “Dvije su riječi lahke na jeziku, teške na Mizanu (Vagi) i drage (mile) Gospodaru: SUBHANALLAHI VE BI HAMDIHI, SUBHANALLAHIL-‘AZIM.” (Sahihu Muslim) ")
        lista.add("Allaha spominjite, i stojeći, i sjedeći, i ležeći.” (En-Nisa’, 103.) ")
        lista.add("Allahov Poslanik, s.a.v.s., rekao: ”Ko na mene donese jedan salavat, Allah na njega donese deset salavata.” (Muslim) ")
        lista.add("“I za one koji se, kada grijeh počine ili kad se prema sebi ogriješe, Allaha sjete i oprost za grijehe svoje zamole…” (Ali Imran, 135.) ")
        lista.add("Skrušeni zakir – onaj koji spominje Allaha, jeste onaj čiji zikr srcem, jezikom i tijelom bude podudaran i jedan drugog prati, pa jezikom stalno spominje, srce mu je stalno budno i svjesno zikrullaha, a skrušenost se pokazuje na njegovim djelima. ")
        lista.add(" ")
        lista.add(" ")



    }

}